# Site settings
title:          Saturday10AM
description:    "대전 IT/개발 커뮤니티"
baseurl:        "/"
url:            "http://sat10am.com"

# Author
author:
  name:         Saturday10Am
  url:          http://sat10am.com
  email:        info@sat10am.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
